[tool.poetry]
name = "pipe"
version = "0.1.0"
description = "Pipe is for piping function calls"
authors = ["David Buckley <buckley.w.david@gmail.com>"]

[tool.poetry.dependencies]
python = "*"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
hypothesis = "^3.76"
